"""click-based command-line interface.

Stdout is reserved for the generated bytes/bits so that output can be piped
directly into Unix tools:

    qrng generate --bits 256 | shasum -a 256
    qrng generate --bits 1024 --format binary > random.bin
"""

from __future__ import annotations

import json
import sys

import click

from . import __version__
from .config import BackendConfig, CircuitConfig, PostProcessConfig, QRNGConfig
from .core.entropy_source import QuantumEntropySource
from .core.processor import EntropyProcessor
from .core.provider import EntropyProvider
from .logging_utils import get_logger
from .verification.benchmark import benchmark_throughput
from .verification.entropy import shannon_entropy
from .verification.nist import monobit_frequency_test


def _build_config(
    device: str,
    precision: str,
    width: int,
    no_von_neumann: bool,
    no_toeplitz: bool,
    ratio: float,
    seed: int | None,
    log_level: str,
) -> QRNGConfig:
    return QRNGConfig(
        backend=BackendConfig(
            device=device,  # type: ignore[arg-type]
            precision=precision,  # type: ignore[arg-type]
            seed_simulator=seed,
        ),
        circuit=CircuitConfig(register_width=width),
        postprocess=PostProcessConfig(
            enable_von_neumann=not no_von_neumann,
            enable_toeplitz=not no_toeplitz,
            toeplitz_output_ratio=ratio,
            toeplitz_seed=seed,
        ),
        log_level=log_level,
    )


def _make_pipeline(cfg: QRNGConfig) -> tuple[EntropyProvider, EntropyProcessor]:
    source = QuantumEntropySource(
        circuit_config=cfg.circuit, backend_config=cfg.backend
    )
    return EntropyProvider(source), EntropyProcessor(cfg.postprocess)


# ---------- Shared options (decorator) ----------
def _common_options(func):
    func = click.option(
        "--device",
        type=click.Choice(["auto", "GPU", "CPU"]),
        default="auto",
        show_default=True,
        help="Aer device selection.",
    )(func)
    func = click.option(
        "--precision",
        type=click.Choice(["single", "double"]),
        default="double",
        show_default=True,
        help="Statevector precision.",
    )(func)
    func = click.option(
        "--width",
        type=click.IntRange(1, 30_000),
        default=24,
        show_default=True,
        help="Hadamard register width (qubits per shot).",
    )(func)
    func = click.option("--no-von-neumann", is_flag=True, help="Disable Von Neumann stage.")(func)
    func = click.option("--no-toeplitz", is_flag=True, help="Disable Toeplitz stage.")(func)
    func = click.option(
        "--ratio",
        type=click.FloatRange(0.01, 0.99),
        default=0.5,
        show_default=True,
        help="Toeplitz output:input ratio.",
    )(func)
    func = click.option("--seed", type=int, default=None, help="Deterministic seed (for testing).")(func)
    func = click.option(
        "--log-level",
        type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]),
        default="WARNING",
        show_default=True,
        help="Logging level (written to stderr).",
    )(func)
    return func


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="qrng")
def cli() -> None:
    """Quantum Random Number Generator."""


@cli.command("generate")
@click.option("--bits", "n_bits", type=click.IntRange(1), required=True, help="Number of bits.")
@click.option(
    "--format",
    "out_format",
    type=click.Choice(["bin", "hex", "binary", "base64"]),
    default="bin",
    show_default=True,
    help="Output format. 'bin' = ASCII 0/1, 'binary' = raw bytes.",
)
@_common_options
def generate(
    n_bits: int,
    out_format: str,
    device: str,
    precision: str,
    width: int,
    no_von_neumann: bool,
    no_toeplitz: bool,
    ratio: float,
    seed: int | None,
    log_level: str,
) -> None:
    """Generate N bits of quantum randomness to stdout."""
    get_logger("qrng", level=log_level)
    cfg = _build_config(device, precision, width, no_von_neumann, no_toeplitz, ratio, seed, log_level)
    provider, processor = _make_pipeline(cfg)

    raw = provider.produce(n_bits, oversample=12.0)
    processed = processor.process(raw.bits, target_bits=n_bits)
    bits = processed.bits

    if out_format == "bin":
        click.echo(bits, nl=True)
    elif out_format == "hex":
        pad = (-len(bits)) % 8
        padded = bits + "0" * pad
        as_bytes = int(padded, 2).to_bytes(len(padded) // 8, "big") if padded else b""
        click.echo(as_bytes.hex(), nl=True)
    elif out_format == "binary":
        pad = (-len(bits)) % 8
        padded = bits + "0" * pad
        as_bytes = int(padded, 2).to_bytes(len(padded) // 8, "big") if padded else b""
        sys.stdout.buffer.write(as_bytes)
        sys.stdout.buffer.flush()
    elif out_format == "base64":
        import base64

        pad = (-len(bits)) % 8
        padded = bits + "0" * pad
        as_bytes = int(padded, 2).to_bytes(len(padded) // 8, "big") if padded else b""
        click.echo(base64.b64encode(as_bytes).decode("ascii"), nl=True)


@cli.command("verify")
@click.option("--bits", "n_bits", type=click.IntRange(128), default=4096, show_default=True)
@click.option(
    "--output",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
)
@_common_options
def verify(
    n_bits: int,
    output: str,
    device: str,
    precision: str,
    width: int,
    no_von_neumann: bool,
    no_toeplitz: bool,
    ratio: float,
    seed: int | None,
    log_level: str,
) -> None:
    """Run NIST monobit + Shannon entropy on a generated sample."""
    get_logger("qrng", level=log_level)
    cfg = _build_config(device, precision, width, no_von_neumann, no_toeplitz, ratio, seed, log_level)
    provider, processor = _make_pipeline(cfg)

    raw = provider.produce(n_bits, oversample=12.0)
    processed = processor.process(raw.bits, target_bits=n_bits)
    bits = processed.bits

    nist = monobit_frequency_test(bits)
    H = shannon_entropy(bits)
    report = {
        "sample_bits": len(bits),
        "nist_monobit": nist.as_dict(),
        "shannon_entropy": H,
        "shannon_entropy_passed": H >= 0.99,
        "backend": provider.source.backend.describe(),
    }
    if output == "json":
        click.echo(json.dumps(report, indent=2))
    else:
        click.echo(f"Sample size       : {len(bits)} bits")
        click.echo(f"NIST Monobit p    : {nist.p_value:.6f} ({'PASS' if nist.passed else 'FAIL'})")
        click.echo(f"Shannon entropy H : {H:.6f} ({'PASS' if H >= 0.99 else 'FAIL'}, target >= 0.99)")
        click.echo(f"Backend           : {provider.source.backend.describe()}")


@cli.command("benchmark")
@click.option("--bits", "n_bits", type=click.IntRange(128), default=4096, show_default=True)
@click.option(
    "--output",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
)
@_common_options
def benchmark(
    n_bits: int,
    output: str,
    device: str,
    precision: str,
    width: int,
    no_von_neumann: bool,
    no_toeplitz: bool,
    ratio: float,
    seed: int | None,
    log_level: str,
) -> None:
    """Measure throughput (bits/s) and per-bit latency."""
    get_logger("qrng", level=log_level)
    cfg = _build_config(device, precision, width, no_von_neumann, no_toeplitz, ratio, seed, log_level)
    provider, processor = _make_pipeline(cfg)
    bench = benchmark_throughput(provider, processor, target_bits=n_bits, oversample=12.0)
    if output == "json":
        click.echo(json.dumps(bench.as_dict(), indent=2))
    else:
        click.echo(f"Total bits        : {bench.total_bits}")
        click.echo(f"Duration          : {bench.duration_seconds:.4f} s")
        click.echo(f"Throughput        : {bench.bits_per_second:,.2f} bits/s")
        click.echo(f"Latency per bit   : {bench.latency_ms_per_bit:.4f} ms/bit")


def main() -> None:  # pragma: no cover - entrypoint
    cli()


if __name__ == "__main__":  # pragma: no cover
    main()
